---
- name: test if earlyoom_version is set correctly
  assert:
    that:
      - earlyoom_version is defined
    quiet: yes

- name: test if earlyoom_clone_destination is set correctly
  assert:
    that:
      - earlyoom_clone_destination is defined
    quiet: yes

- name: test if earlyoom_installation_destination is set correctly
  assert:
    that:
      - earlyoom_installation_destination is defined
    quiet: yes

- name: test if earlyoom_minimum_memory_percent is set correctly
  assert:
    that:
      - earlyoom_minimum_memory_percent is defined
      - earlyoom_minimum_memory_percent is number
      - earlyoom_minimum_memory_percent > 0
      - earlyoom_minimum_memory_percent <= 100
    quiet: yes

- name: test if earlyoom_minimum_swap_percent is set correctly
  assert:
    that:
      - earlyoom_minimum_swap_percent is defined
      - earlyoom_minimum_swap_percent is number
      - earlyoom_minimum_swap_percent > 0
      - earlyoom_minimum_swap_percent <= 100
    quiet: yes

- name: test if earlyoom_memory_report_interval is set correctly
  assert:
    that:
      - earlyoom_memory_report_interval is defined
      - earlyoom_memory_report_interval is number
      - earlyoom_memory_report_interval >= 0
    quiet: yes
