---
# tasks file for earlyoom
- name: install requirements
  package:
    name: "{{ earlyoom_requirements }}"
    state: present
  register: earlyoom_install_requirements
  until: earlyoom_install_requirements is succeeded
  retries: 3

- name: clone repository
  git:
    dest: "{{ earlyoom_clone_destination }}"
    repo: "https://github.com/rfjakob/earlyoom.git"
    version: "{{ earlyoom_version }}"
  register: earlyoom_clone_repository
  until: earlyoom_clone_repository is succeeded
  retries: 3
  notify:
    - make earlyoom
    - install earlyoom

- name: flush handlers
  meta: flush_handlers

- name: create service earlyoom
  import_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: earlyoom
        description: Early Out Of Memory Killer
        start_command: /usr/bin/earlyoom -r 60 -m {{ earlyoom_minimum_memory_percent }} -s {{ earlyoom_minimum_swap_percent }}


- name: start and enable earlyoom
  service:
    name: "{{ earlyoom_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
