---
# tasks file for earlyoom
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install requirements
  package:
    name: "{{ earlyoom_requirements }}"
    state: present

- name: clone repository
  git:
    dest: "{{ earlyoom_clone_destination }}"
    repo: "https://github.com/rfjakob/earlyoom.git"
    version: "{{ earlyoom_version }}"
  notify:
    - make earlyoom
    - install earlyoom

- name: flush handlers
  meta: flush_handlers

- name: create service earlyoom
  import_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: earlyoom
        description: Early Out Of Memory Killer
        start_command: >-
          /usr/bin/earlyoom
          -r {{ earlyoom_memory_report_interval }}
          -m {{ earlyoom_minimum_memory_percent }}
          -s {{ earlyoom_minimum_swap_percent }}
        status_pattern: earlyoom

- name: start and enable earlyoom
  service:
    name: "{{ earlyoom_service }}"
    state: started
    enabled: yes
