---
# handlers file for earlyoom
- name: make earlyoom
  make:
    chdir: "{{ earlyoom_clone_destination }}"

- name: install earlyoom
  copy:
    src: "{{ earlyoom_clone_destination }}/earlyoom"
    dest: "{{ earlyoom_installation_destination }}"
    remote_src: yes

- name: restart earlyoom
  service:
    name: "{{ earlyoom_service }}"
    state: restarted
